<?php

declare(strict_types=1);

namespace Noirapi\Helpers;

use Noirapi\Lib\Controller;
use Noirapi\Lib\Tracy\CurlBarPanel;
use Override;
use Tracy\Debugger;

use function is_object;
use function is_string;

/** @psalm-api  */
class Curl extends \Curl\Curl
{
    private static array $requests = [];

    public function __construct(?string $base_url = null, array $options = [])
    {

        if (! isset(Controller::$panels['curl'])) {
            Controller::$panels['curl'] = true;

            $panel = new CurlBarPanel();
            $panel->title = 'Curl';

            Debugger::getBar()->addPanel($panel);
        }

        parent::__construct($base_url, $options);
    }

    /**
     * @param mixed $handle
     * @return mixed
     */
    #[Override]
    public function exec($handle = null): mixed
    {

        $start = microtime(true);

        $res = parent::exec($handle); // TODO: Change the autogenerated stub

        $info = $this->getInfo();
        $method = $this->getOpt(CURLOPT_CUSTOMREQUEST);

        $post_fields = $this->getOpt(CURLOPT_POSTFIELDS);
        if (! empty($post_fields) && is_string($post_fields)) {
            parse_str($post_fields, $post);
        }
        $this->addLog(
            url: ($method ?? 'POST') . ' ' . $this->getUrl(),
            info: $info['http_code'] . ' ' . $info['content_type'],
            time: microtime(true) - $start,
            request: $post ?? [],
            response: is_object($this->response) || is_array($this->response) ? $this->response : substr((string)$this->response, 0, 128), // phpcs:ignore
        );

        return $res;
    }

    /**
     * @param string $url
     * @param string $info
     * @param float $time
     * @param array $request
     * @param object|array|string|null $response
     *
     * @return void
     *
     * @psalm-external-mutation-free
     */
    public function addLog(string $url, string $info, float $time, array $request, object|array|string|null $response = null): void //phpcs:ignore
    {

        self::$requests[] = [
            'url'      => $url,
            'request'  => $request,
            'info'     => $info,
            'time'     => $time * 1000.0,
            'response' => $response,
        ];
    }

    /**
     * @return array
     *
     * @psalm-external-mutation-free
     */
    public static function getLog(): array
    {

        return self::$requests;
    }
}
